services:
  ever-node:
    image: ever-node
    build:
      context: .
      dockerfile: ./ever-node/Dockerfile
      args:
        TARGET: ${TARGET}
    expose:
      - 30000
    entrypoint: ./run.sh
    command: --node-path ../ever-node --betterscale-tools-path ../betterscale-tools --configs configs/zerostate-config.json --output temp
    volumes:
      - shared-data:/var/everscale/local-ever-network/temp
  jrpc-api:
    image: jrpc-api
    build:
      context: .
      dockerfile: ./jrpc-api/Dockerfile
      args:
        TARGET: ${TARGET}
    expose:
      - 30000
    entrypoint: ./run.sh
    command: --config configs/config.yaml --global-config ../shared/ton-global.config.json
    volumes:
      - shared-data:/var/everscale/shared
    ports:
      - 8081:8081
volumes:
  shared-data:
